TERMINAL.CLEAR()
TERMINAL.STATUS("Boot sequence engaged")
TERMINAL.OVERLAY("BASIC9000 ONLINE", 2000)
PRINT "SYSTEM CHECK: OK"
PRINT "HTTP READY: " + (HTTP.STATUS("https://example.com") = 200)
PRINT "TIME NOW: " + TIME.FORMAT(TIME.NOW(), "YYYY-MM-DD HH:mm:ss")
TERMINAL.STATUS("READY")
